
server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://124.221.214.9:3306/CPT202?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.xjtlu.cpt202.cpt202Project.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#####JWT配置#####
audience:
  # 代表这个JWT的接收对象,存入audience
  aud: 98f6bcd4621d37
  # 密钥, 经过Base64加密, 可自行替换。Base64加解密工具：http://tool.chinaz.com/Tools/Base64.aspx
  base64Secret: Z3VveGl1emhpRXJiYWRhZ2FuZ1dpbnNwYWNlVjMuMA==
  # JWT的签发主体，存入issuer
  iss: issued by ***
  # 过期时间毫秒
  expiresSecond: 172800