
server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    username: yourusername
    password: yourpassword
    url: jdbc:mysql://yourIp/CPT202?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis配置
  redis:
    #Redis服务器地址
    host: yourIp
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 20000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
    #连接超时时间（毫秒）
    timeout: 5000

mybatis:
  type-aliases-package: com.xjtlu.cpt202.cpt202Project.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false

#####JWT配置#####
audience:
  # 代表这个JWT的接收对象,存入audience
  aud: 98f6bcd4621d37
  # 密钥, 经过Base64加密, 可自行替换。Base64加解密工具：http://tool.chinaz.com/Tools/Base64.aspx
  base64Secret: Z3VveGl1emhpRXJiYWRhZ2FuZ1dpbnNwYWNlVjMuMA==
  # JWT的签发主体，存入issuer
  iss: issued by ***
  # 过期时间毫秒
  expiresSecond: 1800000
